In [1]:
import numpy as np

In [3]:
### how to array slicing or indexing using boolean operators
our_array = np.linspace(1,1000,50,dtype=int)
our_array

array([   1,   21,   41,   62,   82,  102,  123,  143,  164,  184,  204,
        225,  245,  266,  286,  306,  327,  347,  367,  388,  408,  429,
        449,  469,  490,  510,  531,  551,  571,  592,  612,  633,  653,
        673,  694,  714,  734,  755,  775,  796,  816,  836,  857,  877,
        898,  918,  938,  959,  979, 1000])

In [4]:

# we only want element greater than 100

greater_100 = our_array > 100
greater_100

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [5]:


# now we will pass boolean array to array

our_array[greater_100]

array([ 102,  123,  143,  164,  184,  204,  225,  245,  266,  286,  306,
        327,  347,  367,  388,  408,  429,  449,  469,  490,  510,  531,
        551,  571,  592,  612,  633,  653,  673,  694,  714,  734,  755,
        775,  796,  816,  836,  857,  877,  898,  918,  938,  959,  979,
       1000])